name: desafio-votacao

services:
  db:
    image: postgres:16.3
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: desafiovotacao2024
      POSTGRES_DB: desafio-votacao
    ports:
      - "5432:5432"
    volumes:
      - desafio-votacao:/var/lib/postgresql/data

volumes:
  desafio-votacao: 